Script started on 2016年03月03日 (週四) 20時54分08秒
]0;AN4046072@2015cpp: ~[01;32mAN4046072@2015cpp[00m:[01;34m~[00m$ whiamil[K;pws[Kd[C[C[1Pami;pwdoami;pwd
AN4046072
/home/AN4046072
]0;AN4046072@2015cpp: ~[01;32mAN4046072@2015cpp[00m:[01;34m~[00m$ git clone https[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kgit config -l
user.name=yunxun
user.email=jeff51925@gmail.com
]0;AN4046072@2015cpp: ~[01;32mAN4046072@2015cpp[00m:[01;34m~[00m$ c[Kgut[K[Kit clone https://[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K clone https://github.com/yun xun/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Compressing objects:  50% (1/2)   [Kremote: Compressing objects: 100% (2/2)   [Kremote: Compressing objects: 100% (2/2), done.[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;AN4046072@2015cpp: ~[01;32mAN4046072@2015cpp[00m:[01;34m~[00m$ ls
[0m[01;34mlab1[0m  lab1.script
]0;AN4046072@2015cpp: ~[01;32mAN4046072@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月03日 (週四) 20時55分36秒
